[package]
name = "goodreads-rs-example"
version = "0.1.0"
authors = ["etoledom <etoledom@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goodreads-rs = { path = "../" }
